### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by akshatnitd** [NJACKWinterOfCode/IMDB_Portal#25]
**Actual Behaviour**
* There is no .gitignore file

**Expected Behaviour**
* There should be a .gitignore file with the standard python .gitignore template and `info.txt` file

**Would you like to work on the issue?**
 Anybody can take this up.

**Comment by agarwalrounak** [comment]
I am working on this issue. 
Just one thing, what about the info.txt file? I didn't understand that.

**Comment by Sai-Adarsh** [comment]
> **Actual Behaviour**
> 
> * There is no .gitignore file
> 
> **Expected Behaviour**
> 
> * There should be a .gitignore file with the standard python .gitignore template and `info.txt` file
> 
> **Would you like to work on the issue?**
> Anybody can take this up.

I'm interested

**Comment by akshatnitd** [comment]
@agarwalrounak @Sai-Adarsh You should add the `info.txt` also in the  `.gitignore`, sinnce this file is created only to check the logs while running.

Also, since @agarwalrounak claimed the issue, he is supposed to work on it.
